// Generated by CoffeeScript 1.4.0
var __slice = [].slice,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    return define(['backbone', 'underscore'], function(Backbone, _) {
      return root.Backbone.Record = factory(Backbone, _);
    });
  } else if (typeof require === 'function' && ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null)) {
    return module.exports = factory(require('backbone'), require('undercore'));
  } else {
    return root.Backbone.Record = factory(root.Backbone, root._);
  }
})(this, function(Backbone, _) {
  var Record, RecordMixin;
  RecordMixin = {
    define: function() {
      var fieldName, recordFields, _i, _len, _results,
        _this = this;
      recordFields = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      this.prototype.recordFields = recordFields;
      _results = [];
      for (_i = 0, _len = recordFields.length; _i < _len; _i++) {
        fieldName = recordFields[_i];
        _results.push((function(fieldName) {
          return Object.defineProperty(_this.prototype, fieldName, {
            get: function() {
              return this.get(fieldName);
            },
            set: function(value) {
              return this.set(fieldName, value);
            }
          });
        })(fieldName));
      }
      return _results;
    }
  };
  Record = (function(_super) {

    __extends(Record, _super);

    function Record() {
      return Record.__super__.constructor.apply(this, arguments);
    }

    _.extend(Record, RecordMixin);

    return Record;

  })(Backbone.Model);
  return {
    Record: Record,
    RecordMixin: RecordMixin
  };
});
